# Generated by Django 4.1.7 on 2023-03-17 09:20

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=None, max_length=150, null=True, validators=[users.validators.validate_password]),
        ),
    ]
